# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-14 15:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=10000)),
                ('transaction_password', models.CharField(max_length=30)),
                ('account_no', models.IntegerField(default=1000, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_accno', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('transaction_password', models.CharField(max_length=30)),
                ('receiver_accno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.Profile', to_field='account_no')),
            ],
        ),
    ]
