# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-15 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='receiver_accno',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender_accno',
            field=models.IntegerField(default=1000),
        ),
    ]
